version: 0.2

phases:
  install:
    commands:
      - curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel 9.0 --install-dir /usr/share/dotnet9
      - echo '{"sdk":{"version":"9.0.313","rollForward":"latestMinor"}}' > /codebuild/global.json
  pre_build:
    commands:
      - /usr/share/dotnet9/dotnet restore AWSCodePipelineDemo/AWSCodePipelineDemo.csproj
  build:
    commands:
      - /usr/share/dotnet9/dotnet build AWSCodePipelineDemo/AWSCodePipelineDemo.csproj
  post_build:
    commands:
      - /usr/share/dotnet9/dotnet publish -c Release -o ./app/ AWSCodePipelineDemo/AWSCodePipelineDemo.csproj
artifacts:
  files:
    - '**/*'