version: 0.2

phases:
  install:
    commands:
      - curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel 9.0
      - export PATH="$PATH:$HOME/.dotnet"
      - dotnet --version
  pre_build:
    commands:
      - dotnet restore AWSCodePipelineDemo/AWSCodePipelineDemo.csproj
  build:
    commands:
      - dotnet build AWSCodePipelineDemo/AWSCodePipelineDemo.csproj
  post_build:
    commands:
      - dotnet publish -c Release -o ./app/ AWSCodePipelineDemo/AWSCodePipelineDemo.csproj
artifacts:
  files:
    - '**/*'